### ISSUE TITLE
Problems when trying to run

### ISSUE THREAD

**Issue by RikkaTotsuka** [wajili/SimpleMMO-fully-automatic-bot#6]
Hi, I'm having problems executing the file, it says there's a problem on line 395 (return driver)
I'm using google version 111.0.5563.111
and the latest python version
Would you be able to help me? Thank you very much in advance
![imagem_2023-12-14_115909139](https://github.com/wajili/SimpleMMO-fully-automatic-bot/assets/89234178/b7a06859-d4b6-47d4-95c7-0193c66ae2c7)
![imagem_2023-12-14_120111068](https://github.com/wajili/SimpleMMO-fully-automatic-bot/assets/89234178/8d5f88bd-68dd-496f-b6fe-5b18ec92daf4)

**Comment by RikkaTotsuka** [comment]
I managed to solve the problem, it was the lack of the necessary packages to understand the syntaxes, Google is opening normally and the page but it lands on the captcha page before logging in and the solenium script tries to find SimpleMMO, I enter the email and password and closes giving these errors:

Traceback (most recent call last):
  File "/home/miguel/PycharmProjects/simplebot/simmmobot.py", line 403, in <module>
    result = main_function()
             ^^^^^^^^^^^^^^^
  File "/home/miguel/PycharmProjects/simplebot/simmmobot.py", line 397, in main_function
    main()
  File "/home/miguel/PycharmProjects/simplebot/simmmobot.py", line 32, in main
    assert "SimpleMMO" in driver.title
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

![Captura de tela de 2023-12-15 18-23-44](https://github.com/wajili/SimpleMMO-fully-automatic-bot/assets/89234178/aa94305e-17db-4c10-84f5-0986771958bc)
